## Nd Array

In [2]:
import numpy as np

#1d array

arr1=np.array([2,4,1,2,5])

arr1=(arr1*5)

print(arr1)

print(arr1.ndim)

# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array 

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  

    
])


[10 20  5 10 25]
1


### Array attributes

In [4]:
#1.demention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#2.shape

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#3.Data_type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#4 size

print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


### ndarray datatype

In [5]:
arr = np.array([1,2,3]) 

print(arr.dtype)

arr = np.array([1.5,2.4,3.2]) 
print(arr.dtype)

int64
float64


In [10]:
#Upcasting 
arr = np.array([1,2,3.2])
print(arr.dtype)

arr = np.array([1,2,3.2,"hello"])
print(arr.dtype)

arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype)


float64
<U32
<U32


In [13]:
#selecting datatype on array


arr = np.array([1,2,30],dtype=np.int8)

print(arr.dtype)

arr=arr.astype(np.int32)

print(arr.dtype)

#error
arr = np.array([1,2,300],dtype=np.int8)

arr = np.array([1,2,3.2,'hello'],dtype=np.float64) 

print(arr.dtype)

OverflowError: Python integer 300 out of bounds for int8

### ndarray creation from existing data

In [21]:
#List
lst=[10,20,30,40,40.5]

arr=np.array(lst , dtype=np.int32)

# print(arr)
# print(type(arr))

# print(arr.dtype)

mixed_lst=[10,"hello",10.5,40]

arr=np.array(mixed_lst)
# print(arr)
# print(type(arr))

# print(arr.dtype)


matrix=[ [3,4,6],
         [4,6,7]
    
]

arr=np.array(matrix)
print(arr)
print(type(arr))

print(arr.dtype)

print(arr.shape)

print(arr.size)

print(arr.ndim)



[[3 4 6]
 [4 6 7]]
<class 'numpy.ndarray'>
int64
(2, 3)
6
2


In [22]:
#tuple 

tpl = (10,20,30) 

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 


int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [26]:
#Set

st={1,2,3}

arr = np.array(list(st))
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 



int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [35]:
#dictionary

dic={
    'a':1,'ad':3,'c':34
}

print(type(dic))

key=dic.keys()

# print(key)

value=dic.values()

# print(value)

items=dic.items()

#keys to ndarray

arr = np.array(list(key))
# print(arr.dtype) 
# arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

# print(items)

<class 'dict'>
['a' 'ad' 'c']
<class 'numpy.ndarray'>
<U2
(3,)
1


In [37]:
#values to ndarray
arr = np.array(list(value))
print(arr) 
arr = arr.astype(np.int16)
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[ 1  3 34]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [38]:
#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '1']
 ['ad' '3']
 ['c' '34']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating Ndarray from scratch

In [44]:
#Zeros

arr=np.zeros((2,3),dtype=np.int32)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)


arr4=np.zeros_like(arr3)

print(arr4)
print(arr4.shape) 
print(arr4.ndim)




[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)
3


In [46]:
#np ones


arr=np.ones((2,3),dtype=np.int32)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr4=np.ones_like(arr3)

print(arr4)
print(arr4.shape) 
print(arr4.ndim)



[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)
3


In [50]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr4=np.empty_like(arr3)

print(arr4)
print(arr4.shape) 
print(arr4.ndim)

[[-80  57 -10]
 [-95 -34   1]
 [  0   0   0]
 [  0   0   0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)
3


In [53]:
#np.full 

arr = np.full((4,3),10)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


# arr = np.full_like(arr3,np.inf,dtype=np.float64) 

# print(arr)
# print(arr.shape)
# print(arr.dtype)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12


## Array creation with random values

In [54]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.95484558 0.93678918 0.26442497]
 [0.52273678 0.05398794 0.86288383]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [59]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (4,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[4 2 7]
 [8 4 3]
 [1 9 9]
 [6 7 1]]
<class 'numpy.ndarray'>
int32
(4, 3)
2
12


In [60]:
# np.random.uniform(start,end, shape)  Floating Number

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[74.9662117  64.57289053 97.47941185 67.15668451]
  [89.85754535 99.143104   72.46045173 98.71511972]
  [70.86248495 98.62877283 90.74907451 78.01118117]]

 [[83.511776   50.841971   55.54612727 72.02722374]
  [75.41052359 54.29372338 62.95219488 88.05720113]
  [63.38290299 50.68186976 81.20870908 68.97303434]]

 [[88.21123318 50.33900016 58.07244825 90.55955943]
  [72.60166274 64.93522521 93.52360855 99.41585085]
  [65.6273805  78.29053266 87.82948484 75.17179562]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## Array creation with range function

In [71]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [74]:
# np.linspace(start , end(included) , koita) 
# 0 theke 4 so er modde thekei 6 ta point nibe tao equally like 0 0.8 0.16 kind of this
arr = np.linspace(0, 4 ,6)


print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [78]:
# np.logspace(start , end(included) , koita ) 

# eikhane basically log base 10 heshe thake e+0 bake 10 bujhai and value gula 10^0 10^2 10^3 thats how synchronize vhabe thake

# base chale manually set kora jaii

arr = np.logspace(0 , 4 ,7,base=2) 

print(arr)

[ 1.          1.58740105  2.5198421   4.          6.34960421 10.0793684
 16.        ]


### creating matrix for Linear algebra

In [80]:
#diagonal matrix
diagonal_matrix=np.diag([1,2,3])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)


In [84]:
# identity matrix 

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)



# np.eye(row , column,k) 


identity_mat=np.eye(3,4,-1)
print(identity_mat)
print(identity_mat.shape)
identity_mat=np.eye(3,4,1)
print(identity_mat)
print(identity_mat.shape)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
(3, 4)
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(3, 4)


## indexing and slicing

In [8]:
#indexing

print(arr1)
# print(arr2)

arr1[2]=100
print(arr1)

print(arr1[2])


# print(arr1)
arr2[0][2]= 100

print(arr2)

[ 10  20 100  10  25]
[ 10  20 100  10  25]
100
[[  1   2 100]
 [  4   5   6]]


In [20]:
#slicing 
#1d = arr[start:end:step] 

# arr_mod=arr1[1:4]

# arr_mod[1]=200

# print(arr1)

# print(arr_mod)

arr_mod=arr1[1:4].copy()

arr_mod[2]=100
print(arr_mod)
print(arr1)

[ 20 200 100]
[ 10  20 200  10  25]


In [15]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

print(arr2) 

getting_row=arr2[0:1:,]
getting_row1=arr2[1::,]

print(getting_row)
print(getting_row1)



#getting a column 

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)


#getting a portion 


portion = arr2[:: , 0:2] 

print(portion)

[[  1   2 100]
 [  4   5   6]]
[[  1   2 100]]
[[4 5 6]]
[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


### Advanced Indexing and Slicing

In [21]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [25]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>1])
arr2[arr2>2] = 0 

print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[  2 100   4   5   6]
[[1 2 0]
 [0 0 0]]


In [24]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


In [26]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]
