In [1]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

In [3]:
print(arr)

b=arr.reshape(5,10)
b

[[ 6 15 60 51 31]
 [79 65 42 61  6]
 [11 44 57 43 98]
 [49 14  4 76 76]
 [54  3  3 82 74]
 [75 94 67 15 88]
 [46 33 73 12 18]
 [63 22 64 37 57]
 [58 70  2 41 55]
 [71 88 99 32 69]]


array([[ 6, 15, 60, 51, 31, 79, 65, 42, 61,  6],
       [11, 44, 57, 43, 98, 49, 14,  4, 76, 76],
       [54,  3,  3, 82, 74, 75, 94, 67, 15, 88],
       [46, 33, 73, 12, 18, 63, 22, 64, 37, 57],
       [58, 70,  2, 41, 55, 71, 88, 99, 32, 69]], dtype=int32)

In [5]:
#row-wise for flattern
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'F') 

print(column_wise_flattening) 

1
[ 6 11 54 46 58 15 44  3 33 70 60 57  3 73  2 51 43 82 12 41 31 98 74 18
 55 79 49 75 63 71 65 14 94 22 88 42  4 67 64 99 61 76 15 37 32  6 76 88
 57 69]


In [6]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))

## Concatenate

In [10]:
# Row wise concatenate
print(a)
print(b)
con_row=np.concatenate((a,b),axis=0)


con_col=np.concatenate((a,b),axis=1)


print(con_row)

print(con_col)

[[2 5 9]
 [4 3 4]]
[[24 20 29]
 [24 22 22]]
[[ 2  5  9]
 [ 4  3  4]
 [24 20 29]
 [24 22 22]]
[[ 2  5  9 24 20 29]
 [ 4  3  4 24 22 22]]


In [12]:
# error 

# row wise concetanate korar shomoi column same thakbe 
# col wise concat korar shomoi row ta same thakte hobe 

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

[[1 5 6]
 [9 8 8]
 [3 3 8]]


In [13]:
mat=np.array([
    [10,20,30],
    [20,40,50]
])

transpose=mat.T
print(transpose)



[[10 20]
 [20 40]
 [30 50]]


In [19]:
#array split

a=np.random.randint(1,10,size=(10,))

print(a)

splited_array=np.array_split(a,3)

print(splited_array)

[5 5 2 3 7 1 2 4 8 4]
[array([5, 5, 2, 3], dtype=int32), array([7, 1, 2], dtype=int32), array([4, 8, 4], dtype=int32)]


In [23]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x % y

print(remainder) 

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [25]:
# mathematical function 

# trigonometry 

# sin , cos , tan takes values in radian 

sin_val = np.sin(x)
print(sin_val) 
cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [28]:
#log 

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x) 
print(two_diye_bhag)


sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [30]:
# different 
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [33]:
#broadcasting 

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2 

print(result)

#rulings = columns er size and vector er size same hote hobe 

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2 

vector = np.array([1,2,3,]) 

result = matrix +vector
print(result)

[ 12  10  18 102]
[[11 22 33]
 [31 42 53]]


### Logical function

In [36]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than=x>y

print(greater_than)

equal = x==y 

print(equal)

# all () -> shob true kina 
# any() -> jekono ekta true ase kina 

print(np.all(greater_than)) 

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


In [39]:
x=np.array([10,8,3,14])

z=x.copy()

print(z)


z.sort()

print(z)

print(x)

[10  8  3 14]
[ 3  8 10 14]
[10  8  3 14]


In [40]:
# copy sorting
print(x)
sort_arr = np.sort(x) 

print(sort_arr)

print(x)

[10  8  3 14]
[ 3  8 10 14]
[10  8  3 14]


In [42]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

#vertical sort
vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [43]:
print(x)

[10  8  3 14]


In [46]:
# np.where( condition , x , y ) if true x , otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>=8,x,0) # returns array 
print(arr)

(array([1]),)
[10  8  0 14]


In [47]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [48]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [50]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

max_value=np.max(x)
min_value=np.min(x)

print(max_value)
print(min_value)
maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

100
8
1
2


## Counting Array

In [51]:
a=np.random.randint(1,100,size=(100,))

print(a)

[10 27 28 52  1 89 39 37 85 21  4 49 29 59 32 29 90  2  3 11 32 69 36 33
 26 48 53 71 74 57 10 41 36 52 20 33 31 24 37 51 47 79 26 89 91 56  1  7
 56 69 60 95 38 70 51 90 31 82 94 41 91 99 20 23 45 96 80 50 29 50 77 66
 27 82 21 33 87 36 47 13  6 83 85 97 33 72 58 59 51 84  6  7  8 74  7 31
 85 98 95 94]


In [52]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

1


In [56]:
unique_value,count=np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 1  2  3  4  6  7  8 10 11 13 20 21 23 24 26 27 28 29 31 32 33 36 37 38
 39 41 45 47 48 49 50 51 52 53 56 57 58 59 60 66 69 70 71 72 74 77 79 80
 82 83 84 85 87 89 90 91 94 95 96 97 98 99]
[2 1 1 1 2 3 1 2 1 1 2 2 1 1 2 2 1 3 3 2 4 3 2 1 1 2 1 2 1 1 2 3 2 1 2 1 1
 2 1 1 2 1 1 1 2 1 1 1 2 1 1 3 1 2 2 2 2 2 1 1 1 1]


# Stattistical Functionalities

In [57]:
#data load 

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data) 

FileNotFoundError: student_scores.csv not found.

In [58]:
data=[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]



SyntaxError: invalid syntax. Perhaps you forgot a comma? (315946247.py, line 1)

In [59]:
# statistics  
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks) 

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)


NameError: name 'data' is not defined

In [60]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [64]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])



# a er column and b er row same length hote hobe 
dot_product = np.dot(A,B)
print(dot_product)


# trace 

#primary diagonal er element er sum holo trace
print(np.trace(B))


# 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [62]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

6.66133814775094e-16
2


In [63]:
x1=np.sin(np.pi/2)
print(x1)

1.0


In [65]:
a=np.array([1,2,3])
b=np.array([1,2,3])

print(a+b)

[2 4 6]


In [67]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(a,b))

14
